spring:
  #Redis配置
  redis:
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:192.168.2.55}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 10000
    common:
      lettuce:
        pool:
          max-active: 3000 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 30 # 连接池中的最大空闲连接
          max-wait: 3000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 10 # 连接池中的最小空闲连接

  jr-live:
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:192.168.2.55}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 10000